
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dblibromante?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 10MB
      
         
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5Dialect

